flist = [
    "ic_add_a_photo_bar_24dp.png",
    "ic_add_a_photo_black_24dp.png",
    "ic_add_bar_24dp.png",
    "ic_add_black_24dp.png",
    "ic_arrow_drop_down_bar_24dp.png",
    "ic_arrow_drop_down_black_24dp.png",
    "ic_arrow_drop_up_bar_24dp.png",
    "ic_arrow_drop_up_black_24dp.png",
    "ic_barrel_black_24dp.png",
    "ic_broom_bar_24dp.png",
    "ic_broom_black_24dp.png",
    "ic_bug_black_24dp.png",
    "ic_bug_report_black_24dp.png",
    "ic_check_box_black_24dp.png",
    "ic_check_off_24dp.png",
    "ic_check_on_24dp.png",
    "ic_cloud_download_black_24dp.png",
    "ic_cloud_upload_black_24dp.png",
    "ic_create_bar_24dp.png",
    "ic_create_black_24dp.png",
    "ic_crop_square_black_24dp.png",
    "ic_delete_bar_24dp.png",
    "ic_delete_black_24dp.png",
    "ic_done_black_24dp.png",
    "ic_down_arrow_black_24dp.png",
    "ic_exit_to_app_black_24dp.png",
    "ic_exit_to_app_grey09_24dp.png",
    "ic_home_black_24dp.png",
    "ic_home_grey09_24dp.png",
    "ic_link_black_24dp.png",
    "ic_math_black_24dp.png",
    "ic_menu_black_24dp.png",
    "ic_more_vert_black_24dp.png",
    "ic_next_black_24dp.png",
    "ic_oval_accent_24dp.png",
    "ic_oval_black_24dp.png",
    "ic_person_black_24dp.png",
    "ic_pin_black_24dp.png",
    "ic_pos_black_24dp.png",
    "ic_prev_black_24dp.png",
    "ic_select_all_bar_24dp.png",
    "ic_select_all_black_24dp.png",
    "ic_settings_black_24dp.png",
    "ic_settings_grey09_24dp.png",
    "ic_share_black_24dp.png",
    "ic_sync_bar_24dp.png",
    "ic_sync_black_24dp.png",
    "ic_sync_grey09_24dp.png",
    "ic_trending_flat_black_24dp.png",
    "ic_undo_bar_24dp.png",
    "ic_undo_black_24dp.png",
    "ic_update_black_24dp.png",
    "ic_up_arrow_black_24dp.png",
    "ic_visibility_black_24dp.png",
    "ic_visibility_off_black_24dp.png",
    "Injection.png",
    "Logbook.png",
     "Rootbook.png",
     "RootbookAbout.png",
     "WaterManagment.png",
]

for f in flist:
    print('<Content Include="$(ResourceDirUWP)\\%s">' % f)
    print("    <Link>Resources\\%s</Link>" % f)
    print("    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>")
    print("</Content>")
