//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Generator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloud.Generator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the back-end generator which was defined via the command line as &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidBackend {
            get {
                return ResourceManager.GetString("InvalidBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing input parameter..
        /// </summary>
        internal static string MissingInput {
            get {
                return ResourceManager.GetString("MissingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No usable namespace was found in the supplied module..
        /// </summary>
        internal static string MissingNamespace {
            get {
                return ResourceManager.GetString("MissingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing output parameter..
        /// </summary>
        internal static string MissingOutput {
            get {
                return ResourceManager.GetString("MissingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing input or output parameters..
        /// </summary>
        internal static string MissingParameters {
            get {
                return ResourceManager.GetString("MissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing type parameter..
        /// </summary>
        internal static string MissingType {
            get {
                return ResourceManager.GetString("MissingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping the class &apos;{0}&apos; because it does not have the Item attribute attached to it..
        /// </summary>
        internal static string SkipClass {
            get {
                return ResourceManager.GetString("SkipClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     The valid back-ends are: ClientSQLite, ServerSQLite, or ServerMySQL..
        /// </summary>
        internal static string ValidBackends {
            get {
                return ResourceManager.GetString("ValidBackends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using -&gt; &apos;{0}&apos; as the primary namespace for the generated classes..
        /// </summary>
        internal static string VerboseNamespace {
            get {
                return ResourceManager.GetString("VerboseNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property          : {0}.
        /// </summary>
        internal static string VerboseType1 {
            get {
                return ResourceManager.GetString("VerboseType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Type           : {0}.
        /// </summary>
        internal static string VerboseType2 {
            get {
                return ResourceManager.GetString("VerboseType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - IsAutoProperty : {0}.
        /// </summary>
        internal static string VerboseType3 {
            get {
                return ResourceManager.GetString("VerboseType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - MaximumSize    : {0}.
        /// </summary>
        internal static string VerboseType4 {
            get {
                return ResourceManager.GetString("VerboseType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - MinimumSize    : {0}.
        /// </summary>
        internal static string VerboseType5 {
            get {
                return ResourceManager.GetString("VerboseType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Default        : {0}.
        /// </summary>
        internal static string VerboseType6 {
            get {
                return ResourceManager.GetString("VerboseType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforming  -&gt; &apos;{0}&apos; into a database class with the properties defined as:.
        /// </summary>
        internal static string VerboseTypeName {
            get {
                return ResourceManager.GetString("VerboseTypeName", resourceCulture);
            }
        }
    }
}
