//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Transaction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloud.Transaction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server..
        /// </summary>
        internal static string ConnectFailure {
            get {
                return ResourceManager.GetString("ConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote connection was closed..
        /// </summary>
        internal static string ConnectionClosed {
            get {
                return ResourceManager.GetString("ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method parameter cannot be null or empty..
        /// </summary>
        internal static string MethodNameInvalid {
            get {
                return ResourceManager.GetString("MethodNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find remote server..
        /// </summary>
        internal static string NameResolutionFailure {
            get {
                return ResourceManager.GetString("NameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong protocol was used for this transmission..
        /// </summary>
        internal static string ProtocolError {
            get {
                return ResourceManager.GetString("ProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A remote call failed.
        /// </summary>
        internal static string ReturnFailure {
            get {
                return ResourceManager.GetString("ReturnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error, could not connect to the SQL server..
        /// </summary>
        internal static string ReturnInternalSQL {
            get {
                return ResourceManager.GetString("ReturnInternalSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        internal static string ReturnInvalidAlphabet {
            get {
                return ResourceManager.GetString("ReturnInvalidAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encoding.
        /// </summary>
        internal static string ReturnInvalidBase64 {
            get {
                return ResourceManager.GetString("ReturnInvalidBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier.
        /// </summary>
        internal static string ReturnInvalidGUID {
            get {
                return ResourceManager.GetString("ReturnInvalidGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index.
        /// </summary>
        internal static string ReturnInvalidInteger {
            get {
                return ResourceManager.GetString("ReturnInvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid key was processed.
        /// </summary>
        internal static string ReturnInvalidKey {
            get {
                return ResourceManager.GetString("ReturnInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key did not match size requirements.
        /// </summary>
        internal static string ReturnInvalidKeySize {
            get {
                return ResourceManager.GetString("ReturnInvalidKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid package supplied.
        /// </summary>
        internal static string ReturnInvalidPackage {
            get {
                return ResourceManager.GetString("ReturnInvalidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter validation failed.
        /// </summary>
        internal static string ReturnInvalidParameterList {
            get {
                return ResourceManager.GetString("ReturnInvalidParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request body.
        /// </summary>
        internal static string ReturnInvalidRequest {
            get {
                return ResourceManager.GetString("ReturnInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid string was read.
        /// </summary>
        internal static string ReturnInvalidString {
            get {
                return ResourceManager.GetString("ReturnInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid alpha numeric string was processed.
        /// </summary>
        internal static string ReturnInvAlphNum {
            get {
                return ResourceManager.GetString("ReturnInvAlphNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        internal static string ReturnInvEmail {
            get {
                return ResourceManager.GetString("ReturnInvEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid number was processed.
        /// </summary>
        internal static string ReturnInvId {
            get {
                return ResourceManager.GetString("ReturnInvId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid number was processed.
        /// </summary>
        internal static string ReturnInvNum {
            get {
                return ResourceManager.GetString("ReturnInvNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access to the server.
        /// </summary>
        internal static string ReturnNoAccess {
            get {
                return ResourceManager.GetString("ReturnNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect.
        /// </summary>
        internal static string ReturnNoConnection {
            get {
                return ResourceManager.GetString("ReturnNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such identifier.
        /// </summary>
        internal static string ReturnNoID {
            get {
                return ResourceManager.GetString("ReturnNoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such user.
        /// </summary>
        internal static string ReturnNoUser {
            get {
                return ResourceManager.GetString("ReturnNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error Undefined SQL exception.
        /// </summary>
        internal static string ReturnSQLCacthAll {
            get {
                return ResourceManager.GetString("ReturnSQLCacthAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error a SQL command failed..
        /// </summary>
        internal static string ReturnSQLCommand {
            get {
                return ResourceManager.GetString("ReturnSQLCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error, could not connect to the SQL server.
        /// </summary>
        internal static string ReturnSQLConnection {
            get {
                return ResourceManager.GetString("ReturnSQLConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error a SQL delete command failed.
        /// </summary>
        internal static string ReturnSQLDelete {
            get {
                return ResourceManager.GetString("ReturnSQLDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error a SQL read command failed..
        /// </summary>
        internal static string ReturnSQLRead {
            get {
                return ResourceManager.GetString("ReturnSQLRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result is undefined.
        /// </summary>
        internal static string ReturnUndefined {
            get {
                return ResourceManager.GetString("ReturnUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect over a secure channel..
        /// </summary>
        internal static string SecureChannelFailure {
            get {
                return ResourceManager.GetString("SecureChannelFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A complete request could not be sent to the remote server..
        /// </summary>
        internal static string SendFailure {
            get {
                return ResourceManager.GetString("SendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to establish a connection with the server.\nThe connection timed out.
        /// </summary>
        internal static string TimeoutFailure {
            get {
                return ResourceManager.GetString("TimeoutFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error . . . .
        /// </summary>
        internal static string UnknownFailure {
            get {
                return ResourceManager.GetString("UnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown transaction error occurred..
        /// </summary>
        internal static string UnknownTransaction {
            get {
                return ResourceManager.GetString("UnknownTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user key parameter cannot be null or empty..
        /// </summary>
        internal static string UserKeyInvalid {
            get {
                return ResourceManager.GetString("UserKeyInvalid", resourceCulture);
            }
        }
    }
}
