//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Store {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloud.Store.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load credentials..
        /// </summary>
        public static string CredentialLoadFailed {
            get {
                return ResourceManager.GetString("CredentialLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Base64 supplied as a query argument.
        /// </summary>
        public static string InvalidBase64 {
            get {
                return ResourceManager.GetString("InvalidBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in the supplied query argument.
        /// </summary>
        public static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encryption string..
        /// </summary>
        public static string InvalidEncryptionString {
            get {
                return ResourceManager.GetString("InvalidEncryptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GUID supplied as a query argument.
        /// </summary>
        public static string InvalidGUID {
            get {
                return ResourceManager.GetString("InvalidGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer supplied as a query argument.
        /// </summary>
        public static string InvalidInteger {
            get {
                return ResourceManager.GetString("InvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data supplied as a key field..
        /// </summary>
        public static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter list..
        /// </summary>
        public static string InvalidParamList {
            get {
                return ResourceManager.GetString("InvalidParamList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data supplied as a value field..
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessKey cannot be null or empty..
        /// </summary>
        public static string NullAccessKey {
            get {
                return ResourceManager.GetString("NullAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignemtList cannot be null or empty..
        /// </summary>
        public static string NullAssignemtList {
            get {
                return ResourceManager.GetString("NullAssignemtList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author cannot be null or empty..
        /// </summary>
        public static string NullAuthor {
            get {
                return ResourceManager.GetString("NullAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column cannot be null or empty..
        /// </summary>
        public static string NullColumn {
            get {
                return ResourceManager.GetString("NullColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashKey cannot be null or empty..
        /// </summary>
        public static string NullHashKey {
            get {
                return ResourceManager.GetString("NullHashKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyList cannot be null or empty..
        /// </summary>
        public static string NullKeyList {
            get {
                return ResourceManager.GetString("NullKeyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPassword cannot be null or empty..
        /// </summary>
        public static string NullNewPassword {
            get {
                return ResourceManager.GetString("NullNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be null or empty..
        /// </summary>
        public static string NullPassword {
            get {
                return ResourceManager.GetString("NullPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table cannot be null or empty..
        /// </summary>
        public static string NullTable {
            get {
                return ResourceManager.GetString("NullTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserKey cannot be null or empty..
        /// </summary>
        public static string NullUserKey {
            get {
                return ResourceManager.GetString("NullUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName cannot be null or empty..
        /// </summary>
        public static string NullUsername {
            get {
                return ResourceManager.GetString("NullUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        public static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueList cannot be null or empty..
        /// </summary>
        public static string NullValueList {
            get {
                return ResourceManager.GetString("NullValueList", resourceCulture);
            }
        }
    }
}
