//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloud.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the supplied credential file..
        /// </summary>
        internal static string CredentialLoadError {
            get {
                return ResourceManager.GetString("CredentialLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be null or empty..
        /// </summary>
        internal static string DateNullError {
            get {
                return ResourceManager.GetString("DateNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a string identifier..
        /// </summary>
        internal static string Exception1 {
            get {
                return ResourceManager.GetString("Exception1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting a colon character after a string identifier..
        /// </summary>
        internal static string Exception2 {
            get {
                return ResourceManager.GetString("Exception2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is not well formed..
        /// </summary>
        internal static string Exception3 {
            get {
                return ResourceManager.GetString("Exception3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting a value, object or an array assignment..
        /// </summary>
        internal static string Exception4 {
            get {
                return ResourceManager.GetString("Exception4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item added without a valid name..
        /// </summary>
        internal static string InvalidMenuItem {
            get {
                return ResourceManager.GetString("InvalidMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the supply key file..
        /// </summary>
        internal static string KeyLoadError {
            get {
                return ResourceManager.GetString("KeyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the true, false, or null keywords.
        /// </summary>
        internal static string KeywordError {
            get {
                return ResourceManager.GetString("KeywordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of file unexpectedly reached when parsing the buffer.
        /// </summary>
        internal static string PrematureEOF {
            get {
                return ResourceManager.GetString("PrematureEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time cannot be null or empty..
        /// </summary>
        internal static string TimeNullError {
            get {
                return ResourceManager.GetString("TimeNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined character.
        /// </summary>
        internal static string UndefinedCharacter {
            get {
                return ResourceManager.GetString("UndefinedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined escape sequence character.
        /// </summary>
        internal static string UndefinedEscape {
            get {
                return ResourceManager.GetString("UndefinedEscape", resourceCulture);
            }
        }
    }
}
