//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookStore.Cli.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}&gt;.
        /// </summary>
        internal static string ActionPrompt {
            get {
                return ResourceManager.GetString("ActionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  list           Pulls all books from the server and prints them to the console
        ///  clear          Clears the entire book table
        ///
        ///  selectArray    Pulls a list of all server id and revision pairs
        ///                  The list is in the form of [id[0], rev[0] ... id[n], rev[n]]
        ///
        ///  save           Creates, or updates an element with the contents of the supplied JSON
        ///                   [string|file] JSON
        ///
        ///  selectById     Pulls a book item with the specified id
        ///  deleteById     Deletes an item with the sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning this will clear the Book table. Are you sure? (yes)/(no).
        /// </summary>
        internal static string BookClearMessage {
            get {
                return ResourceManager.GetString("BookClearMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   list       Prints the current configuration
        ///
        ///  host       Sets the host address to the supplied argument
        ///               [string] Host Ipv4 address or domain name
        ///  
        ///  port       Sets the host port to the supplied argument
        ///               [int] Port in the set [80, 443, 1024-65535]
        ///  
        ///  timeout    Sets the timeout for store transactions
        ///               [int] Time in milliseconds in the range of [10-30000]
        ///  .
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ConnectedMessage {
            get {
                return ResourceManager.GetString("ConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the supplied value as an integer.
        /// </summary>
        internal static string IntConversionFail {
            get {
                return ResourceManager.GetString("IntConversionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character 0x{0:2X}.
        /// </summary>
        internal static string InvalidChar {
            get {
                return ResourceManager.GetString("InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host name supplied.
        /// </summary>
        internal static string InvalidHost {
            get {
                return ResourceManager.GetString("InvalidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port range supplied. Ports are limited to [80,443, 1024-65535].
        /// </summary>
        internal static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented.
        /// </summary>
        internal static string MessageNA {
            get {
                return ResourceManager.GetString("MessageNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string NotConnectedMessage {
            get {
                return ResourceManager.GetString("NotConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0}&apos; was not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  clear     Clears the console
        ///  ping      Tests the connection to the database
        ///
        ///  config    Handles settings related to the connection with the host
        ///  book      Handles book API objects
        ///                See [item help] for more information
        ///
        ///  quit      Exits the program
        ///.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connection to: {0}:{1}.
        /// </summary>
        internal static string PingMessage {
            get {
                return ResourceManager.GetString("PingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0} {1}&apos; was not found.
        /// </summary>
        internal static string ReadActionNotFound {
            get {
                return ResourceManager.GetString("ReadActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the supplied input.
        /// </summary>
        internal static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read a valid integer from the console.
        /// </summary>
        internal static string ReadInvalidInt {
            get {
                return ResourceManager.GetString("ReadInvalidInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read a valid string from the console.
        /// </summary>
        internal static string ReadInvalidString {
            get {
                return ResourceManager.GetString("ReadInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to select by the supplied id &apos;{0}&apos;.
        /// </summary>
        internal static string SelectError {
            get {
                return ResourceManager.GetString("SelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set the timeout.
        /// </summary>
        internal static string TimeoutFail {
            get {
                return ResourceManager.GetString("TimeoutFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown option: &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownOption {
            get {
                return ResourceManager.GetString("UnknownOption", resourceCulture);
            }
        }
    }
}
