//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookStore.Cli.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}&gt;.
        /// </summary>
        internal static string ActionPrompt {
            get {
                return ResourceManager.GetString("ActionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///book: &lt;action&gt;
        ///
        ///    &lt;action&gt; is one of the following:
        ///
        ///          help - Displays this screen.
        ///          list - Pulls all books from the server and prints them to the console.
        ///         clear - Clears the entire book store.
        ///
        ///   selectArray - Pulls a list of all server id and revision pairs.
        ///                    The list is in the form of [id[0], rev[0] ... id[n], rev[n]]
        ///
        ///   selectById  - Pulls a book item with the specified id.
        ///                    &lt;int&gt; Server id
        ///
        ///.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning this will clear the Book table. Are you sure? (yes)/(no).
        /// </summary>
        internal static string BookClearMessage {
            get {
                return ResourceManager.GetString("BookClearMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///config: &lt;action&gt;
        ///
        ///    &lt;action&gt; is one of the following:
        ///
        ///          help - Displays this screen.
        ///          list - Prints the current configuration.
        ///
        ///          host - Sets the host address to the supplied argument.
        ///                    &lt;string&gt; Host Ipv4 address or domain name.
        ///
        ///          port - Sets the host port to the supplied argument.
        ///                    &lt;int&gt; Port in the set [80, 443, 1024-65535]
        ///
        ///       timeout - Sets the timeout for store transactions.
        ///                    &lt;int&gt; Time in  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ConnectedMessage {
            get {
                return ResourceManager.GetString("ConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the supplied value as a 32bit integer..
        /// </summary>
        internal static string IntConversionFail {
            get {
                return ResourceManager.GetString("IntConversionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host name supplied.
        /// </summary>
        internal static string InvalidHost {
            get {
                return ResourceManager.GetString("InvalidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port range supplied. Ports are limited to [80,443, 1024-65535].
        /// </summary>
        internal static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to determine the sub command for the input string &apos;{0}&apos;.
        /// </summary>
        internal static string MissingArgument {
            get {
                return ResourceManager.GetString("MissingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string NotConnectedMessage {
            get {
                return ResourceManager.GetString("NotConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;action&gt;
        ///
        ///    &lt;action&gt; is one of the following:
        ///
        ///          help - Displays this screen.
        ///          quit - Exits the program.
        ///         clear - Clears the console.
        ///          ping - Tests the connection to the database.
        ///
        ///        config - Handles settings related to the store database connection.
        ///                    See &lt;config&gt; &lt;help&gt; for more information.
        ///
        ///          book - Handles book API objects.
        ///                    See &lt;book&gt; &lt;help&gt; for more information.
        ///.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to read a valid integer from the console..
        /// </summary>
        internal static string ReadInvalidInt {
            get {
                return ResourceManager.GetString("ReadInvalidInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to read a valid string from the console..
        /// </summary>
        internal static string ReadInvalidString {
            get {
                return ResourceManager.GetString("ReadInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set the timeout.
        /// </summary>
        internal static string TimeoutFail {
            get {
                return ResourceManager.GetString("TimeoutFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown option: &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownOption {
            get {
                return ResourceManager.GetString("UnknownOption", resourceCulture);
            }
        }
    }
}
