//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Generator.ServerSQLite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloud.Generator.ServerSQLite.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     
        ///    /// &lt;summary&gt;
        ///    /// Auto generated from the &apos;${InterfaceName}&apos; interface.
        ///    /// &lt;/summary&gt;
        ///    public class ${ClassName} : ${InterfaceName}
        ///    {
        ///        public const int UniqueIdentifier = ${UniqueId};
        ///
        ///        [PrimaryKey, AutoIncrement]
        ///        public int Identifier { get; set; } = Defaults.Constants.InvalidIdentifier;
        ///
        ///        // Defines the primary means to index elements in the database.
        ///        public string  Key { get; set; } = string.Empty;
        ///
        ///        [Ignore]
        ///        publ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     /// &lt;summary&gt;
        ///    /// Provides the means log a message without knowing
        ///    /// a specific output method.
        ///    /// &lt;/summary&gt;
        ///    public interface ILog
        ///    {
        ///        void WriteLine(string message);
        ///    }
        ///
        ///    namespace Defaults
        ///    {
        ///        public static class Constants
        ///        {
        ///            public static int InvalidIdentifier = -9999;
        ///        }
        ///
        ///        /// &lt;summary&gt;
        ///        /// Provides support for a default logger if one is not set; goes through System.Console.
        ///        /// &lt;/summary&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///-------------------------------------------------------------------------------
        ///    Copyright (c) Charles Carley.
        ///
        ///  This software is provided &apos;as-is&apos;, without any express or implied
        ///  warranty. In no event will the authors be held liable for any damages
        ///  arising from the use of this software.
        ///
        ///  Permission is granted to anyone to use this software for any purpose,
        ///  including commercial applications, and to alter it and redistribute it
        ///  freely, subject to the following restrictions:
        ///
        ///  1.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
    }
}
